src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank( message = "Vous devez saisir un nom" )
     * @Assert\Length(min ="2", minMessage="Votre nom doit faire minimum {{ limit }} caractères")
     */
    private $name;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\GreaterThan("today", message="La date de début doit être dans le futur.")
     */
    private $start_at;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\GreaterThan("today", message="La date de début doit être dans le futur.")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lientinker;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *  @Assert\Length(
     *      min = 20,
     *      max = 200,
     *      minMessage = "Votre description doit contenir au moins {{ limit }} caractères",
     *      maxMessage = "Votre description doit contenir au maximum {{ limit }} caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThan("today")
     */
    private $deadline_at;

    /**
     * @ORM\Column(type="float", nullable=true)
     * @Assert\Type(
     *     type="float", message="Vous devez saisir un prix valide")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(
     *     maxSize = "4000k",
     *     mimeTypes = {"application/pdf", "application/x-pdf", "image/jpg", "image/png", "image/jpeg"},
     *     mimeTypesMessage = "Vous n'avez pas ajouter de fichier.")
     */
    private $picture;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=true)
     */
    private $weight;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $width;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $length;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $height;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="project", orphanRemoval=true)
     */
    private $pictures;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="project")
     */
    private $users;


    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLientinker(): ?string
    {
        return $this->lientinker;
    }

    public function setLientinker(?string $lientinker): self
    {
        $this->lientinker = $lientinker;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDeadlineAt(): ?\DateTimeInterface
    {
        return $this->deadline_at;
    }

    public function setDeadlineAt(?\DateTimeInterface $deadline_at): self
    {
        $this->deadline_at = $deadline_at;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getWeight()
    {
        return $this->weight;
    }

    public function setWeight($weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getWidth()
    {
        return $this->width;
    }

    public function setWidth($width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getLength()
    {
        return $this->length;
    }

    public function setLength($length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getHeight()
    {
        return $this->height;
    }

    public function setHeight($height): self
    {
        $this->height = $height;

        return $this;
    }


    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setProject($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getProject() === $this) {
                $photo->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addProject($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeProject($this);
        }

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, array(
                'label' => "Nom du projet :",
                'attr' => array(
                    'placeholder' => "Exemple : Joystick 2.0"
                ),
            ))
            ->add('description', TextareaType::class, array(
                'label' => "Description :",
                'attr' => array(
                'placeholder' => "Exemple : Ceci est un Joystick adapté spécifiquement pour ..."
                )
            ))
            ->add('deadline_at', null, array(
                'widget' => 'choice',
                'label' => 'Au plus tard :'
            ))
            ->add('picture', FileType::class, array(
                'label' => 'Photo :',
                'attr' => array(
                    'placeholder' => "Photo format : PDF, JPG, PNG, JPEG :"
                ),
            ))
            ->add('weight', null, array(
                'label' => 'Paramètre du projet :',
                'attr' => array(
                    'placeholder' => "Poids de l'objet en gramme."
                ),
            ))
            ->add('width', null, array(
                'label' => false,
                'attr' => array(
                    'placeholder' => "Largeur de l'objet en centimètre."
                ),
            ))
            ->add('length', null, array(
                'label' => false,
                'attr' => array(
                    'placeholder' => "Longueur de l'objet en centimètre."
                ),
            ))
            ->add('height', null, array(
                'label' => false,
                'attr' => array(
                    'placeholder' => "Hauteur de l'objet en centimètre."
                ),
            ))
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php
namespace App\Controller;

use App\Entity\User;
use App\Entity\Project;
use App\Form\ProjectType;
use App\Service\ProjectService;
use App\Service\FileUploaderService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class ProjectController extends AbstractController
{
    /**
     * @Route("/project", name="project_list")
     */
    public function list( Request $request, ProjectService $projectService ){
        $query = $request->query->get( 'query' );
        $sort = $request->query->get( 'sort', 'id' );
        if( !empty( $query ) ){
            $projects = $projectService->search( $query, $sort );
        }else{
            $projects = $projectService->getAll( $sort );
        }
        return $this->render( 'project/list.html.twig', array(
            'projects' => $projectService->getAll(),
        ));
    }
    /**
     * @Route("/project/add", name="project_add")
     */
    public function add( Request $request, FileUploaderService $fileUploaderService)
    {
        $project = new Project();
        $form = $this->createForm( ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $project->setStartAt(new \DateTime());
            $project->setCreatedAt(new \DateTime());
            
            // $file stocke le fichier PDF téléchargé
            $file = $form->get('picture')->getData();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            try {
                $file->move(
                    $this->getParameter('pictures_directory'),
                    $fileName
                );  
            } catch (FileException $e) {  
            // gérer l'exception si quelque chose se passe pendant le téléchargement du fichier
            }

            // met à jour la propriété 'brochure' pour stocker le nom du fichier PDF au lieu de son contenu
            $project->setPicture($fileName);

            $em = $this->getDoctrine()->getManager();
            $em->persist( $project );
            $em->flush();

            return $this->redirectToRoute( 'project_list', array(
                'id' => $project->getId(),
        ));
        }
        
        return $this->render( 'project/add.html.twig', array(
            'form' => $form->createView(),
        ));
    }


    /**
     * @return string
     */
    private function generateUniqueFileName(){
        // md5() rend un nom fichier unique et uniqid() est basé sur la date.
        return md5(uniqid());
    }
    
    public function new(Request $request, FileUploaderService $fileUploaderService) {
        
    }

    /**
     * @Route("/project/{id}", name="project_show", requirements={"id"="\d+"})
     */
    public function show( ProjectService $projectService, $id ){
        $project = $projectService->get( $id );
        if( empty( $project ) ){
            return new Response( 'Project Not Found', 404 );
        }
        return $this->render( 'project/show.html.twig', array(
            'project' => $project,
        ));
    }
    


}

templates/project/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un projet - {{ parent() }}{% endblock %}

{% block body %}
{{ form_start ( form ) }}
    <div class="container my-4">

    {{ form_widget ( form ) }}
            <button class="btn btn-primary ml-auto" type="submit">Ajouter</button>
    </div>
{{ form_end ( form ) }}

{% block footer %}{% endblock %}
{% endblock %}

templates/project/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos projets - {{ parent() }}{% endblock %}

{% block body %}

<div class="container text-center">
    
    <div class="projects my-4">
        <div class="row">
            {% for project in projects %}
            <div class="col-md-6 col-lg-4">
                <div class="card project my-3 shadow">
                    <div class="project-picture" style="background-image: url('{{ project.picture }}');">
                        {% if date() < date( project.deadlineAt ) %}
                            <span class="badge badge-pill badge-warning">A venir</span>
                        {% else %}
                            <span class="badge badge-pill badge-success">Réalisé</span>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ project.name|slice(0,27) }}</h5>
                        <div class="project-info">
                            <div class="row">
                                <div class="col-sm-6 col-12">
                                    <div class="row">
                                        <div class="col-6">
                                            <span>
                                                <i class="fab fa-osi"></i>
                                            </span>
                                        </div>
                                        <div class="col-6">
                                            <span>
                                                <p class="hoverP">
                                                    {{ ( project.price ) ? project.price : 'oss' }}
                                                    <span class="hoverpoid">Abréviation conventionnée de "Open Source".</span> 
                                                </p>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6 col-12">
                                    <div class="row project-info2">
                                        <div class="col-6">
                                            <span>
                                                <i class="fas fa-weight-hanging"></i>
                                            </span>
                                        </div>
                                        <div class="col-6">
                                            <span>
                                                <p class="hoverP">                                                
                                                    {{ ( project.weight ) ? project.weight : 'inconnu' }} 
                                                    <span class="hoverpoid">Le poids est indiqué en gramme.</span> 
                                                </p>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p class="card-text card-description">{{ project.description|slice(0,80) }}...</p>
                        
                        <a href="{{ path( 'project_show', { id: project.id } ) }}" class="btn btn-primary">Fiche projet complète</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }} - {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row my-2">
            <div class="col-lg-8 col-sm-12">
                <iframe title="visuel du projet : {{ project.name }}" class="ifram-show" width="725" height="455" src="{{ project.lientinker }}" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
                <iframe title="visuel du projet : {{ project.name }}" class="ifram-show-sm d-lg-none" width="600" height="455" src="{{ project.lientinker }}" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
                <iframe title="visuel du projet : {{ project.name }}" class="d-sm-none" width="450" height="455" src="{{ project.lientinker }}" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
            </div>

            <div class="card col-lg-4 col-sm-12 shadow" style="width: 20rem;">
                <div class="card-header">
                    <h2 class="text-center">{{ project.name }}</h2>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Créée {{ project.deadlineAt|date('d/m/Y') }}</li>
                    <li class="list-group-item">Poids {{ project.weight }} g</li>
                    <li class="list-group-item">Largeur {{ project.width }} cm</li>
                    <li class="list-group-item">Longueur {{ project.length }} cm</li>
                    <li class="list-group-item">Hauteur {{ project.height }} cm</li>
                    <li class="list-group-item">{{ ( project.price ) ? project.price : 'Gratuit' }}</li>
                </ul>
                
            </div>
        </div>
        <div class="cadre my-2 p-2 shadow"><p class="text-center">{{ project.description }}</p></div>
    </div>

</div>
{% block footer %}{% endblock %}
{% endblock %}